replicaCount: 3
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
image:
  repository: jrebaza01/k8s-app
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
