apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jreb-123/.ks8-final-project'
    targetRevision: HEAD
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
