apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jreb-123/k8s-final-project.git'
    path: charts/app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
