name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          chmod +x ./build-and-push.sh
          ./build-and-push.sh
      - name: Set image tag
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV