name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jrebaza01/app:${{ github.sha }}
          file: ./app/Dockerfile
          context: ./app

      - name: Helm Lint
        run: helm lint charts/app

      - name: Helm Template (dry-run)
        run: helm template app charts/app --set image.repository=jrebaza01/app --set image.tag=${{ github.sha }}

      - name: K8s Dry-Run (syntax validation)
        run: |
          helm template app charts/app --set image.repository=jrebaza01/app --set image.tag=${{ github.sha }} \
          | kubectl apply --dry-run=client -f -
