name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Helm Lint
        run: helm lint charts/app

      - name: Helm Template
        run: helm template charts/app

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and Push Docker Image (with cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            jrebaza01/k8s-app:${{ env.TAG }}
            jrebaza01/k8s-app:latest
          # cache-from: type=registry,ref=jrebaza01/k8s-app:cache
          # cache-to: type=registry,ref=jrebaza01/k8s-app:cache,mode=max
